apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_PASSWORD: Githiga#123
  MYSQL_USER: admin
  MYSQL_DATABASE: ecommerce_db
  JWT_SECRET: A7DvGfk9gmr/kjYiPPaFuMdsLv2E7GGbptGqkq8texI=
