{{- $existingConfigMap := lookup "v1" "ConfigMap" .Values.namespace "ecommerce-config" -}}
{{- if not $existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  MYSQL_HOST: {{ .Values.config.data.MYSQL_HOST | quote }}
  MYSQL_PORT: {{ .Values.config.data.MYSQL_PORT | quote }}
  MYSQL_DATABASE: {{ .Values.config.data.MYSQL_DATABASE | quote }}
  SERVER_PORT: {{ .Values.config.data.SERVER_PORT | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.data.SPRING_PROFILES_ACTIVE | quote }}
{{- end }}
