{{- $existingSecret := lookup "v1" "Secret" .Values.namespace "ecommerce-secret" -}}
{{- if and .Values.secrets.create (not $existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: ecommerce
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.data.MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.data.MYSQL_PASSWORD | quote }}
  MYSQL_USER: {{ .Values.secrets.data.MYSQL_USER | quote }}
  MYSQL_DATABASE: {{ .Values.secrets.data.MYSQL_DATABASE | quote }}
  JWT_SECRET: {{ .Values.secrets.data.JWT_SECRET | quote }}
{{- end }}
