services:
  java-backend:
    image: ${DOCKER_HUB_USERNAME}/ecommerce-backend:${IMAGE_TAG:-latest}
    container_name: ecommerce-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://${RDS_ENDPOINT}/${MYSQL_DATABASE} # ← RDS endpoint
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
