spring.application.name=Ecommerce

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:8080}


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.main.banner-mode=off

jwt.secret=D58GUcj5JAdkWShAiwHz/TZRngXe1zNimWyUOPw0+NM=
jwt.expiration-ms=86400000

app.cors.allowed-origins=https://d3gjug8s3pi22r.cloudfront.net



