# application-docker.properties
spring.datasource.url=jdbc:mysql://mysql-db:3306/ecommerce
spring.datasource.username=appuser
spring.datasource.password=apppass

# create will always build tables from your entities on startup
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=D58GUcj5JAdkWShAiwHz/TZRngXe1zNimWyUOPw0+NM=
jwt.expiration-ms=86400000