spring.application.name=Ecommerce

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.port=${SERVER_PORT:8080}

# ✅ Change create to update — never use create in production
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.main.banner-mode=off

#  use environment variable
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# use environment variable
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}